---
creation_rules:
  - # IMPORTANT: This rule MUST be above the others
    path_regex: talos/.*\.sops\.ya?ml
    key_groups:
      - age:
          - "age1vymtmrgfz0s76q9hz0mdy7ku4semj4qh92x6h38eyen3vxaea5dq0ak0zy"
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - "age1vymtmrgfz0s76q9hz0mdy7ku4semj4qh92x6h38eyen3vxaea5dq0ak0zy"
