apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:IBoc+xV4E7KtKigathxLdf/CUwbcpmerrieaMyRTVINA/wuHAdX/Iw==,iv:ruyNJVIBzlos1DlIlTkINvFXfSeOVjWv3KBwvXe0VrE=,tag:YW0u4MROtYIfgN2Pmr9afw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vymtmrgfz0s76q9hz0mdy7ku4semj4qh92x6h38eyen3vxaea5dq0ak0zy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cjQ0dTgraERKOEgwUE42
            QlpPWklSdXNlWmtNcTUzeFpISUpyK3JuU1ZBClIyVGptRWJyNTRUckZrRXZnNDZN
            NUQ0YVg2Wmx5aUJoSzNMRFdMRitNREEKLS0tIGhiZ244SGIrNjM1ODcxNzJuenZ2
            SWRsS3MrY1Y2QUp5b0VIc0Y2c0RUWm8KrxZJ8OzMWl3ima62osE6sVwdAc23vCVp
            4hy9VDk9S9zW9ZPEVE9RoET3GIa79pPsYCk4V2IWRkP2zrkHsWYMYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-20T07:10:40Z"
    mac: ENC[AES256_GCM,data:ti+ef9xeOA7bvNylGmiKfIWgYcg9PekqU4o/E4myCt8ka+NNTyxpd+HnhRqvc30KTKDC27Lsj86sClByMHcvRpgSPsoqSa1O5VzNpYPYEyWvbfBcVsob6tHGGfkoW94j8cHZuj4vjcUoWjBKWjVy8NunzhIQ+aIcESi86D5Tp6E=,iv:A3IgV1je5DOhxY29pdAAZxcq3gYpoQc3Ehf73RgwaAU=,tag:GUtkF0eE7DQdSQcOFfxgXw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
