apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:ZJLuLiz+M0g/fmAbgXEsZsVLmZdSjnKGaUDfpT756V4Fantt1svgJA==,iv:dIf2kMQ7WJolNk/Nshy21nyUm+X110hk8zAdTTDbTMY=,tag:Wh19L904xNSNHdBT4hFkRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vymtmrgfz0s76q9hz0mdy7ku4semj4qh92x6h38eyen3vxaea5dq0ak0zy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFbEU2QmhOSkpnOFNWY3dR
            Ky85NDVFNUhoY3I1YUw5V0FQRStGNEtidURRClNNLzdwbkRTU3lWOWRaKzJNazB0
            VVNqNnhId2F1alpMYm43WW1FNGxnSGMKLS0tIDVudU5zU2FvekZ0N1N1L213QzVz
            aVlwQjREekJOVjFtT2JYa1JkS0JKV1kKZLhu3P3nc7ukWTX5x1AkjS4NJ9841JY/
            UFHqLYbDsgV3IRVPAJI4FyUJwl07nGgxaEfI0vkffzBtJIxiO91ykg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-20T06:30:33Z"
    mac: ENC[AES256_GCM,data:OZ6iD7L8jMRAQw8EvckBuyaqZdCiaL1KN2xvTPFRopEYiC5le3HuxRlZRmpJZvVDFWVzzxIhW7BAuJEdAXEui+Z5f9bgTbqbmlptYJb2CP+SFlTtTdq0aBkjWxAW0upt38GDKDiOZNjegW9s7wXVpa0ewnMSvXfGB3Z+18xjp+c=,iv:9KE9gQewnaR+ApV1gKz7daHyTOSEOuMob8qQK1ZJBXw=,tag:escROU9Vak/+vUYxwcyS6w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
