apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:y3Logx5j9p/SyNSB9GqFun9gUAHQhH/8Q8qOA5++VVfO5TpS4XEfDg==,iv:rurxcBDrV/2Y1nvYhVvqq2i8r/NzmeCbmhlT9i0y6UI=,tag:lpO1wirQgK4H0vBn03kqgA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vymtmrgfz0s76q9hz0mdy7ku4semj4qh92x6h38eyen3vxaea5dq0ak0zy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQjZlaHRQSTc1NmxvRFkx
            VzBpeFFuWGZEeEtxMXQ0emV3dnR2Wm5PeFJVClIxVWdVa1JkL0xheWJKbVpxbGtz
            WFVKTnllVVZyNWZnZW5JT2x5K2VaTkEKLS0tIFlhQm9ZMDFsVXpuTlh4NUJveXpT
            Q1ZQSHZqRFVveWpTaDhEYnRDaUxIdjAK6L2MCq+aZr+vdpHXj0VkhPF2v7KfMoEi
            Xemf4wLVeO0Kg5qTibJhBISOZ1/wEmbSE2FddzEeEvYUk3Kiaoc2uw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-20T08:21:33Z"
    mac: ENC[AES256_GCM,data:mO8x31/CDBNFopwSb6h5swgcWARKnAtBmwLETlFZLpBgMMvKHZXbClLzlvA8iY6n4TU9FSqqH8t0gayPYJUo0HtTIpqeQWdV2UBw0Cca7ouEh9GnTSRqTirzQKqXyfheUmXn67/QZAhVsuUB72dc7xNdKJyXCh5fZTNrfGF9cfU=,iv:/4J6Il9EbFQDeKRUO88Zz2pZHxxbP2xg+gZHrQ94Has=,tag:qqUhs0DPCwHN+s6ft5Kc6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
