apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:CBqA3M+zmrWwAz9H2NX5i/RcLZpTpeim2Tae8kJFPubsDIe8JeprIw==,iv:hZDNZcE1g6BpmpoX1sJTA+ooRETTxYHbX75NaifOdYw=,tag:t7FLUwSTSWsXkLiSLrzgjQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vymtmrgfz0s76q9hz0mdy7ku4semj4qh92x6h38eyen3vxaea5dq0ak0zy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkY0ttbEZjdzd6cUYyUU5U
            OEZjOVpscW9BY3FxbFJWcGFndUh6V1h0Z1RzCnBsNVhGQUtUZExUL2pKUXRyR0Ns
            UVJad1Q3WU4reGR5RkJiRjUxQ3JjYlkKLS0tIHAzL2ZiZ1JZakU4S2NFdUR6MkQz
            cFhCUEJMSHdKYmpDUUFGdkZJem9pOGMKEy/kFHQj84fvCh49RXGa4G2nkYv6whal
            vdluw6Y0nncw6syW85LV7z87oQHRQmpea3JYeWIhswE8OUtqrj4mEQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-20T07:09:35Z"
    mac: ENC[AES256_GCM,data:LHBVebQvKKwVdmanFugItvHUTRJHr2/wf20PFQvLqNGi8zKAio11a3Uzi0D/VYdriSxYC0noQZZnVJ1c7q+um6yKfeYfH32IZ2l37rVxJnVuRwiplBO4/Q4ijI0C/8tmDXRxi40mrFONp0mL+idjPS0rQoqEAJe+C8hlY5LTwuM=,iv:ydA/9Fg7Jv8SG6YOUvLAcnzrHvwR3pE7oijBRReRENk=,tag:edwJZznyJheZj4tBqsEwbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
